apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone-template
spec:
  templates:
    - name: git-clone
      inputs:
        parameters:
          - name: repo
            value: https://github.com/SiyaAmonkar/Argo.git # git-repo link 
        artifacts:
           - name: argo-source  
             path: /src  # src folder where the repository is cloned
             git:
               repo: "{{inputs.parameters.repo}}"
      script:
        image: ubuntu:16.04 # script executing python script and retrieving script execution status
        command: [bash]
        source: |
          apt-get update
          apt-get -y install python
          ls
          cd /src
          ls
          python helloworld.py
          if [ $? -eq 0 ] 
          then
            echo "Successfullt executed"
            exit 0
          else
            echo "Could not execute"
            exit 1
          fi