apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-slack-template
spec:
  templates:
    - name: post-message-slack
      inputs:
        parameters:
          - name: workflowname
          - name: status
      script:
        image: ubuntu:16.04 # script to post message on slack channel based on the input parameters passed
        command: [sh]
        source: |
          apt-get update
          apt-get -y install curl 
          curl -X POST -H 'Content-type: application/json' --data '{"text":"{{inputs.parameters.workflowname}}:{{inputs.parameters.status}}"}' https://hooks.slack.com/services/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